""" 기본 """
DEFAULT_COLOR = "#F0F0F0"

""" 프로세스 상태 """
GOOD_COLOR = "#ACCA69"
SUSPECT_COLOR = "#F6BB43"
WARNING_COLOR = "#F05650"

""" 배경 """
BACKGROUND_FRAME_COLOR = "#FFFFFF"

""" 좌석 상태 """
SEAT_ONLINE_COLOR = DEFAULT_COLOR
SEAT_OFFLINE_COLOR = "#AAAAAA"

""" 녹화 색상 """
RECORDING_COLOR = "#C89696"
